name: Multirunner Tester
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, linux, x64, scope:general, image:debian:stable-slim]
    steps:
      - name: Say hello from bash
        run: bash -c "echo \"Hello from the multirunner test workflow; Running on $(hostname)\""
      - name: Get connectivity info
        run: bash -c "curl -s https://connectivity.maingron.com/json-response.json?template=default"
      - name: Compute Primes
        run: bash -c "echo \"Computing primes\" && seq 2 10000000 | factor | awk 'NF==2{print \$1}' > /dev/null"
  test2:
    runs-on: [self-hosted, linux, x64, scope:general, image:debian:stable-slim]
    steps:
      - name: Say hello from bash
        run: bash -c "echo \"Hello from the multirunner test workflow; Running on $(hostname)\""
      - name: Get connectivity info
        run: bash -c "curl -s https://connectivity.maingron.com/json-response.json?template=default"
      - name: Compute Primes
        run: bash -c "echo \"Computing primes\" && seq 2 10000000 | factor | awk 'NF==2{print \$1}' > /dev/null"
  test3:
    runs-on: [self-hosted, linux, x64, scope:general, image:debian:stable-slim]
    steps:
      - name: Say hello from bash
        run: bash -c "echo \"Hello from the multirunner test workflow; Running on $(hostname)\""
      - name: Get connectivity info
        run: bash -c "curl -s https://connectivity.maingron.com/json-response.json?template=default"
      - name: Compute Primes
        run: bash -c "echo \"Computing primes\" && seq 2 10000000 | factor | awk 'NF==2{print \$1}' > /dev/null"
  test4:
    runs-on: [self-hosted, linux, x64, scope:general, image:debian:stable-slim]
    steps:
      - name: Say hello from bash
        run: bash -c "echo \"Hello from the multirunner test workflow; Running on $(hostname)\""
      - name: Get connectivity info
        run: bash -c "curl -s https://connectivity.maingron.com/json-response.json?template=default"
      - name: Compute Primes
        run: bash -c "echo \"Computing primes\" && seq 2 10000000 | factor | awk 'NF==2{print \$1}' > /dev/null"
  test5:
    runs-on: [self-hosted, linux, x64, scope:general, image:debian:stable-slim]
    steps:
      - name: Say hello from bash
        run: bash -c "echo \"Hello from the multirunner test workflow; Running on $(hostname)\""
      - name: Get connectivity info
        run: bash -c "curl -s https://connectivity.maingron.com/json-response.json?template=default"
      - name: Compute Primes
        run: bash -c "echo \"Computing primes\" && seq 2 10000000 | factor | awk 'NF==2{print \$1}' > /dev/null"
